#include <stdlib.h>
#include <stdio.h>
#include <assert.h>

int main () {
	int i = 10;
	int *j = NULL;
	printf("aaa\n");
	/*assert(*j=0x123456);
	  gitpod /workspace/Study_C $ ./a.out
	  aaa
	  Segmentation fault (core dumped)
	  */
	assert(j=NULL);
	/*
	   gitpod /workspace/Study_C $ ./a.out
	   aaa
	   a.out: assert.c:14: main: Assertion `j=NULL' failed.
	   Aborted (core dumped)
	   */

	while (i) {
		printf("%d ", i);
		assert(i < 3);
		i--;
	}
	return 0;
}

/*

   gitpod /workspace/Study_C $ gcc -DNDEBUG assert.c
   gitpod /workspace/Study_C $ ./a.out
   10 9 8 7 6 5 4 3 2 1

   gitpod /workspace/Study_C $ gcc assert.c
   gitpod /workspace/Study_C $ ./a.out
   a.out: assert.c:9: main: Assertion `i<3' failed.
   Aborted (core dumped)

   Core was generated by `./a.out'.
   Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fa96b0d6535 in __GI_abort () at abort.c:79
#2  0x00007fa96b0d640f in __assert_fail_base (
fmt=0x7fa96b262858 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
assertion=0x55c5f115c011 "i<3", file=0x55c5f115c008 "assert.c", line=9,
function=<optimized out>) at assert.c:92
#3  0x00007fa96b0e6142 in __GI___assert_fail (
assertion=0x55c5f115c011 "i<3", file=0x55c5f115c008 "assert.c", line=9,
function=0x55c5f115c015 <__PRETTY_FUNCTION__.2885> "main")
at assert.c:101
#4  0x000055c5f115b191 in main ()
*/